### ISSUE TITLE
empty <archive></archive> tag crashes a build

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#135]
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line
116, in execute
    skip_pbuild=self.skip_pbuilder)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line
300, in build
    reportpath, self.targetfs )
  File "/usr/lib/python2.7/dist-packages/elbepack/dump.py", line 198, in
elbe_report
    with xml.archive_tmpfile() as fp:
  File "/usr/lib/python2.7/dist-packages/elbepack/elbexml.py", line 285,
in archive_tmpfile
    fp.write( standard_b64decode( self.text("archive") ) )
  File "/usr/lib/python2.7/base64.py", line 93, in standard_b64decode
    return b64decode(s)
  File "/usr/lib/python2.7/base64.py", line 73, in b64decode
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not None

Exception:
must be string or buffer, not None

**Comment by manut** [comment]
fixed 72a7c88215470b199e00dab1116a8cba0316e90e
