### ISSUE TITLE
elbe buildchroot with a xml file including the <setsel/> tag is broken

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#15]
The applied file "var/cache/elbe/pkg-selections" is not generated before
(see elbepack/filesystems.py:250)

Also the mount/umount stuff there should be reworked. Currently the dpkg --set-selections quits with
an exceptions and then the mounts are not umounted.

**Comment by manut** [comment]
For over a year nobody cared. I added a testcase to the testspec: 2c46fbec9f5872a7b88d4609e8668ceb12829ae9

**Comment by manut** [comment]
tests still fail, however the behaviour is different

00:45:02.276 running cmd +chroot <elbepack.efilesystem.TargetFs object at 0x7f9170094ed0> dpkg --clear-selections+
00:45:02.277 ------------------------------------------------------------------------------
00:45:02.277 /bin/sh: 1: cannot open elbepack.efilesystem.TargetFs: No such file
00:45:02.277 ------------------------------------------------------------------------------
00:45:02.277 
00:45:02.277 Command failed with errorcode 2
00:45:02.277 Build failed
00:45:02.277 Traceback (most recent call last):
00:45:02.277   File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line 116, in execute
00:45:02.277     skip_pbuild=self.skip_pbuilder)
00:45:02.277   File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 249, in build
00:45:02.277     self.log, self.get_rpcaptcache() )
00:45:02.277   File "/usr/lib/python2.7/dist-packages/elbepack/efilesystem.py", line 106, in extract_target
00:45:02.277     log.chroot (dst, "dpkg --clear-selections")
00:45:02.277   File "/usr/lib/python2.7/dist-packages/elbepack/asciidoclog.py", line 80, in chroot
00:45:02.277     self.do( chcmd, **args )
00:45:02.277   File "/usr/lib/python2.7/dist-packages/elbepack/asciidoclog.py", line 72, in do
00:45:02.277     raise CommandError(cmd, ret)
00:45:02.277 CommandError
00:45:02.277 
00:45:02.277 
00:45:02.277 Exception:
00:45:02.277 
00:45:02.277

**Comment by manut** [comment]
fixed
