### ISSUE TITLE
elbe control set_xml prints backtrace

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#151]
elbe control set_xml prints a backtrace, however the xml is successfully loaded and a follow up build reflects the changes.

this is only in devel/elbe-3.0 and probably caused by the SDK feature merge.

sh../elbe control set_xml /var/cache/elbe/4db9682b-6e4d-4761-aa7d-2ee0ebc34858 examples/armhf-ti-beaglebone-black.xml

Stacktrace

return: 5

Standard Error

Server returned error:

Traceback (most recent call last):
  File "/var/cache/elbe/devel/elbepack/daemons/soap/faults.py", line 179, in wrapped
    return func(self, arg1, arg2, arg3, arg4, arg5)
  File "/var/cache/elbe/devel/elbepack/daemons/soap/esoap.py", line 97, in upload_file
    uid, builddir, url_validation=ValidationMode.NO_CHECK)
  File "/var/cache/elbe/devel/elbepack/projectmanager.py", line 141, in open_project
    builddir, logpath, url_validation=url_validation)
  File "/var/cache/elbe/devel/elbepack/db.py", line 467, in load_project
    url_validation=url_validation)
  File "/var/cache/elbe/devel/elbepack/elbeproject.py", line 182, in __init__
    self.xml, self.log, self.chrootpath, clean=False)
  File "/var/cache/elbe/devel/elbepack/rfs.py", line 45, in __init__
    self.debootstrap()
  File "/var/cache/elbe/devel/elbepack/rfs.py", line 180, in debootstrap
    raise DebootstrapException()
DebootstrapException: Debootstrap Failed

**Comment by manut** [comment]
solved by putting sdk generation into extra chroot
