### ISSUE TITLE
 local variable 'retry' referenced before assignment in soapclient.py

### ISSUE THREAD

**Issue by QuickJack** [Linutronix/elbe#171]
The build finishes successfully, but an error is thrown in the end.

```
Saving generated Files to elbe-build-20180628-160645
source.xml 	(Current source.xml of the project)
sdcard.img.gz 	(Image)
licence.txt 	(License file)
licence.xml 	(xml License file)
validation.txt 	(Package list validation result)
elbe-report.txt 	(Report)
log.txt 	(Log file)
bin-cdrom.iso 	(Repository IsoImage)
src-cdrom.iso 	(Repository IsoImage)
Traceback (most recent call last):
  File "/elbe/elbe", line 55, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/elbe/elbepack/commands/control.py", line 161, in run_command
    action.execute(control, opt, args[1:])
  File "/elbe/elbepack/soapclient.py", line 516, in execute
    client.download_file(builddir, f.name, dst_fname)
  File "/elbe/elbepack/soapclient.py", line 89, in download_file
    retry = retry - 1
UnboundLocalError: local variable 'retry' referenced before assignment
elbe control get_files Failed
Giving up
elbe_build
elbe_build
```

The variable retry at https://github.com/Linutronix/elbe/blob/1fb72f395a64d373294986ddea1683f727613468/elbepack/soapclient.py#L89 is indeed not declared anywhere.

**Comment by manut** [comment]
Thanks for your report. This is a known issue currently discussed on the elbe-devel@linutronix.de ML, hopefully be fixed very soon!
