### ISSUE TITLE
elbe debianize is broken

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#181]
bricked by:

pylint: debianize: only set attributes in constructor: c56f9de54d7b20566fbf6ebd9d2c8f3f99de7a7c

 % ~/projects/elbe/elbe/elbe debianize                                                              (16:36 - 18-10-08)
Traceback (most recent call last):
  File "/home/local/projects/elbe/elbe/elbe", line 55, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/home/local/projects/elbe/elbe/elbepack/commands/debianize.py", line 22, in run_command
    Debianize(debianizer).run()
  File "/usr/lib/python2.7/dist-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/usr/lib/python2.7/dist-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/usr/lib/python2.7/dist-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/usr/lib/python2.7/dist-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/usr/lib/python2.7/dist-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/usr/lib/python2.7/dist-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/usr/lib/python2.7/dist-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/usr/lib/python2.7/dist-packages/npyscreen/wgwidget.py", line 458, in edit
    self._edit_loop()
  File "/usr/lib/python2.7/dist-packages/npyscreen/wgwidget.py", line 474, in _edit_loop
    self.get_and_use_key_press()
  File "/usr/lib/python2.7/dist-packages/npyscreen/wgwidget.py", line 610, in get_and_use_key_press
    self.handle_input(ch)
  File "/usr/lib/python2.7/dist-packages/npyscreen/wgwidget.py", line 71, in handle_input
    self.handlers[_input](_input)
  File "/usr/lib/python2.7/dist-packages/npyscreen/wgbutton.py", line 97, in h_toggle
    self.when_pressed_function()
  File "/home/local/projects/elbe/elbe/elbepack/debianize/base.py", line 128, in on_ok
    self.debianize()
  File "/home/local/projects/elbe/elbe/elbepack/debianize/kernel.py", line 67, in debianize
    self.deb['loadaddr'] = self.loadaddr.get_value()
AttributeError: 'NoneType' object has no attribute 'get_value'
local@slartibartfast ~/src/linux

**Comment by manut** [comment]
fixed by 44033ca6bbae44f1ce182ff50d3df853ea794cc0
