### ISSUE TITLE
Initvm creation failes in v2.9.13

### ISSUE THREAD

**Issue by QuickJack** [Linutronix/elbe#186]
Traceback (most recent call last):
  File "/elbe/elbe", line 52, in <module>
    mod = __import__(modname)
  File "/elbe/elbepack/commands/init.py", line 18, in <module>
    from elbepack.debinstaller import copy_kinitrd, NoKinitrdException
  File "/elbe/elbepack/debinstaller.py", line 27, in <module>
    from gpgme import Context
ImportError: No module named gpgme
'elbe init' Failed
Giving up

**Comment by QuickJack** [comment]
OK, I forgot to rebuild the docker image.
