### ISSUE TITLE
build src-cdrom.iso fails on verifying dsc if signed with EdDSA

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#196]
When a dsc is inserted into a repository the signature is verified.
The recently added gnupg2_2.1.18-8~deb9u3.dsc has a signature made
with EdDSA instead of RSA. This Algorithm is not supported by the
gnupg version used in jessie. This yields an error.

```
running cmd +reprepro --keepunreferencedfiles --export=never --basedir
"/var/cache/elbe/7591259d-7f60-4318-867f-12cd4a6d164f/srcrepo" -C main -P normal -S misc includedsc
stretch
/var/cache/elbe/7591259d-7f60-4318-867f-12cd4a6d164f/chroot/var/cache/elbe/sources/gnupg2_2.1.18-8~deb9u3.
dsc+
------------------------------------------------------------------------------
gpgme returned an general error verifing signature with '6C1F1EDECC50FA53' in
'/var/cache/elbe/7591259d-7f60-4318-867f-12cd4a6d164f/chroot/var/cache/elbe/sources/gnupg2_2.1.18-8~deb9u3
.dsc'!
Try running gpg --verify
'/var/cache/elbe/7591259d-7f60-4318-867f-12cd4a6d164f/chroot/var/cache/elbe/sources/gnupg2_2.1.18-8~deb9u3
.dsc' manually for hints what is happening.
If this does not print any errors, retry the command causing this message.
There have been errors!
------------------------------------------------------------------------------

Command failed with errorcode 251
Build failed
Traceback (most recent call last):
  File "/var/cache/elbe/devel/elbepack/asyncworker.py", line 158, in execute
    skip_pbuild=self.skip_pbuilder)
  File "/var/cache/elbe/devel/elbepack/elbeproject.py", line 572, in build
    self.build_cdroms(build_bin, build_sources, cdrom_size)
  File "/var/cache/elbe/devel/elbepack/elbeproject.py", line 406, in build_cdroms
    xml=self.xml)
  File "/var/cache/elbe/devel/elbepack/cdroms.py", line 72, in mk_source_cdrom
    repo.includedsc(dsc, force=True)
  File "/var/cache/elbe/devel/elbepack/repomanager.py", line 282, in includedsc
    self._includedsc(path, self.repo_attr.codename, component)
  File "/var/cache/elbe/devel/elbepack/repomanager.py", line 269, in _includedsc
    path)
  File "/var/cache/elbe/devel/elbepack/asciidoclog.py", line 62, in do
    raise CommandError(cmd, ret)
CommandError
```

**Comment by manut** [comment]
Note, that the referenced commit is only a workaround.

To solve the issue the initvm needs to use a newer gpg version.
If this is done, the referenced fix should be reverted!
