### ISSUE TITLE
When I try to build a buster image with elbe 9 by issuing "elbe buildchroot test.xml -t test" in the vm created by "elbe initrd create" I get the following error msg:

### ISSUE THREAD

**Issue by torbenh3** [Linutronix/elbe#231]
The issue is still there. When I try to build a buster image with elbe 9 by issuing "elbe buildchroot test.xml -t test" in the vm created by "elbe initrd create" I get the following error msg:

```
Keys imported
/usr/bin/python2: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Traceback (most recent call last):
  File "/usr/bin/elbe", line 55, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/usr/lib/python2.7/dist-packages/elbepack/commands/buildchroot.py", line 104, in run_command
    opt.skip_pbuild)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 533, in build
    self.install_packages(self.buildenv)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 897, in install_packages
    raise AptCacheUpdateError(e)
elbepack.elbeproject.AptCacheUpdateError: Error Updating rpcaptcache: 
```

When I try to execute the following python script I get the same error:

```
#!/usr/bin/env python
# aptinstall.py

import os
import apt
import sys

os.chroot('test/chroot')
cache = apt.cache.Cache()
cache.update()
cache.open()
```

So probably elbe is using different versions of libc and libnss_files after chroot?

_Originally posted by @mrelyb in https://github.com/Linutronix/elbe/issues/205#issuecomment-514181750_

**Comment by bene42** [comment]
More info needed. Please reopen if nessesary.
