### ISSUE TITLE
ERROR: elbe debianize (missing file)

### ISSUE THREAD

**Issue by jneuhauser** [Linutronix/elbe#238]
On my debian stretch the elbe debianize command on a linux kernel fails every time because of a missing file...
The file `/usr/lib/python2.7/dist-packages/elbepack/makofiles/debianize/kernel/control.mako` is missing.

A quick search with apt-file results in:
```
$ apt-file search /usr/lib/python2.7/dist-packages/elbepack/makofiles/debianize/kernel/control.mako
elbe-debianize: /usr/lib/python2.7/dist-packages/elbepack/makofiles/debianize/kernel/control.mako
```

I´ve reinstalled the packages many times but it didn´t helped.

My used elbe packages:
```
elbe - 11+deb9+build741
elbe-debianize - 11+deb9+build741
```

**If i download the package with apt-get download and extract it, there is this file also missing!**
The debian package **elbe-debianize_9+deb9+build641_all.deb** is the last one which includes this missing file...

For completeness, here the error trace:
```
$ elbe debianize
Traceback (most recent call last):
  File "/usr/bin/elbe", line 55, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/usr/lib/python2.7/dist-packages/elbepack/commands/debianize.py", line 22, in run_command
    TUI(detect_panel())()
  File "/usr/lib/python2.7/dist-packages/elbepack/debianize/base/tui.py", line 102, in __call__
    TUI.loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python2.7/dist-packages/elbepack/debianize/widgets/grid.py", line 130, in keypress
    return super(Grid, self).keypress(size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python2.7/dist-packages/elbepack/debianize/widgets/button.py", line 44, in keypress
    emit_signal(self, TUISignal.CLICK)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python2.7/dist-packages/elbepack/debianize/widgets/form.py", line 57, in confirm
    self.on_submit(data)
  File "/usr/lib/python2.7/dist-packages/elbepack/debianize/panels/base.py", line 102, in on_submit
    self.debianize()
  File "/usr/lib/python2.7/dist-packages/elbepack/debianize/panels/kernel.py", line 72, in debianize
    f.write(template(mako, self.deb))
  File "/usr/lib/python2.7/dist-packages/elbepack/templates.py", line 30, in template
    return Template(filename=fname).render(**d)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 412, in _compile_from_file
    data = util.read_file(filename)
  File "/usr/lib/python2.7/dist-packages/mako/util.py", line 365, in read_file
    fp = open(path, mode)
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/dist-packages/elbepack/makofiles/debianize/kernel/control.mako'
```

**Comment by torbenh3** [comment]
There were a lot more files missing from the elbe-debianize package.
Patch is in the pipe.

Until the next release, you can use elbe debianize directly from a git checkout.
