### ISSUE TITLE
Building Example-XML fails

### ISSUE THREAD

**Issue by ArashJavan** [Linutronix/elbe#240]
Hello and thanks for building elbe!
I have following issues right now, i am trying to build the example xml-file form the elbe exampels
` armhf-ti-beaglebone-black.xml`, but at the last step it fails building with follwoing exception:

```
[CMD] cp -av /var/cache/elbe/initvm-bin-repo "/var/cache/elbe/cf7da170-5fde-4857-9d87-c660b7e3d28d/binrepo"
[ERROR] /var/cache/elbe/initvm-bin-repo does not exist
The generated CDROM will not contain initvm pkgs
This happened because the initvm was probably
generated with --skip-build-bin
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elbepack/cdroms.py", line 138, in mk_binary_cdrom
    do('cp -av /var/cache/elbe/initvm-bin-repo "%s"' % repo_path)
  File "/usr/lib/python2.7/dist-packages/elbepack/shellhelper.py", line 115, in do
    raise CommandError(cmd, p.returncode)
CommandError
cp: cannot stat '/var/cache/elbe/initvm-bin-repo': No such file or directory
[CMD] mkdir -p "/var/cache/elbe/cf7da170-5fde-4857-9d87-c660b7e3d28d/binrepo"
[CMD] mv /var/cache/elbe/cf7da170-5fde-4857-9d87-c660b7e3d28d/chroot/repo /var/cache/elbe/cf7da170-5fde-4857-9d87-c660b7e3d28d/chroot/../
[CMD] rm /var/cache/elbe/cf7da170-5fde-4857-9d87-c660b7e3d28d/chroot/etc/apt/sources.list.d/local.list
[CMD] rm /var/cache/elbe/cf7da170-5fde-4857-9d87-c660b7e3d28d/chroot/etc/apt/trusted.gpg.d/elbe-localrepo.gpg
[ERROR] Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line 181, in execute
    skip_pbuild=self.skip_pbuilder)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 625, in build
    self.build_cdroms(build_bin, build_sources, cdrom_size)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 456, in build_cdroms
    self.builddir)
  File "/usr/lib/python2.7/dist-packages/elbepack/cdroms.py", line 150, in mk_binary_cdrom
    repo = CdromInitRepo(init_codename, repo_path, mirror)
  File "/usr/lib/python2.7/dist-packages/elbepack/repomanager.py", line 343, in __init__
    "Elbe InitVM Cdrom Repo")
  File "/usr/lib/python2.7/dist-packages/elbepack/repomanager.py", line 89, in __init__
    repo_conf = self.fs.read_file("conf/distributions")
  File "/usr/lib/python2.7/dist-packages/elbepack/filesystem.py", line 229, in read_file
    fp = self.open(path, "r")
  File "/usr/lib/python2.7/dist-packages/elbepack/filesystem.py", line 70, in open
    return open(self.fname(path), mode)
IOError: [Errno 2] No such file or directory: '/var/cache/elbe/cf7da170-5fde-4857-9d87-c660b7e3d28d/binrepo/conf/distributions'
```
I tried it multiple times but it always ends with the same exception!
What am i doing wrong?

Thanks

**Comment by torbenh3** [comment]
You are seeing a Bug in elbe-12.1
It it fixed in elbe-12.2 which was released on the 20th of october.
You need to rebuild the initvm after upgrading to elbe 12.2
