### ISSUE TITLE
md5 error

### ISSUE THREAD

**Issue by coveritytest** [Linutronix/elbe#255]
Keys imported
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line 158, in execute
    skip_pbuild=self.skip_pbuilder)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 533, in build
    self.install_packages(self.buildenv)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 904, in install_packages
    dump_initvmpkgs(self.xml)
  File "/usr/lib/python2.7/dist-packages/elbepack/dump.py", line 60, in dump_initvmpkgs
    instpkgs = get_initvm_pkglist()
  File "/usr/lib/python2.7/dist-packages/elbepack/dump.py", line 25, in get_initvm_pkglist
    pkglist = [APTPackage(p) for p in cache if p.is_installed]
  File "/usr/lib/python2.7/dist-packages/elbepack/aptpkgutils.py", line 113, in __init__
    imd5 = pkg.installed and pkg.installed.md5
  File "/usr/lib/python2.7/dist-packages/apt/package.py", line 789, in md5
    return self._records.md5_hash
SystemError: error return without exception set

Exception:
error return without exception set

**Comment by bgermann** [comment]
This is from Elbe <= 11. Please only report errors that are not fixed in the current version.
