### ISSUE TITLE
soapclient timeout

### ISSUE THREAD

**Issue by coveritytest** [Linutronix/elbe#258]
I: Extracting libfdisk1...
I: Extracting libmount1...
I: Extracting libsmartcols1...
I: Extracting libuuid1...
I: Extracting mount...
I: Extracting util-linux...
I: Extracting liblzma5...
I: Extracting zlib1g...
[CMD] cp /usr/bin/qemu-arm-static /var/cache/elbe/3d9edc32-67ce-4fd7-8468-644a8b2f59fc/chroot/usr/bin
[CMD] chroot /var/cache/elbe/3d9edc32-67ce-4fd7-8468-644a8b2f59fc/chroot /debootstrap/debootstrap --second-stage
I: Installing core packages...
timed out
socket error during wait busy occured, retry..

socket error during wait busy occured, retry..

socket error during wait busy occured, retry..

socket error during wait busy occured, retry..

socket error during wait busy occured, retry..

I know it's not very helpful, but I do not get any other log or warnings. When I killed the process I got:

Traceback (most recent call last):
  File "/home/adm/Desktop/elbe/elbe", line 55, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/home/adm/Desktop/elbe/elbepack/commands/control.py", line 169, in run_command
Traceback (most recent call last):
  File "./elbe", line 55, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/home/adm/Desktop/elbe/elbepack/commands/initvm.py", line 98, in run_command
    action.execute(control, opt, args[1:])
  File "/home/adm/Desktop/elbe/elbepack/soapclient.py", line 602, in execute
    action.execute(directory, opt, args[1:])
  File "/home/adm/Desktop/elbe/elbepack/initvmaction.py", line 643, in execute
    submit_and_dl_result(xmlfile, cdrom, opt)
  File "/home/adm/Desktop/elbe/elbepack/initvmaction.py", line 290, in submit_and_dl_result
    system('%s control wait_busy "%s"' % (elbe_exe, prjdir))
  File "/home/adm/Desktop/elbe/elbepack/shellhelper.py", line 36, in system
    time.sleep(0.1)
KeyboardInterrupt
    ret = call(cmd, shell=True, env=new_env)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

I'm on v12.2.

**Comment by bgermann** [comment]
A patch is available at http://lists.linutronix.de/pipermail/elbe-devel/2020-February/003773.html

Either reduce your archive files or apply this patch in the installed files in your initvm.
