### ISSUE TITLE
error installing initvm

### ISSUE THREAD

**Issue by peccehu** [Linutronix/elbe#345]
Hi everybody, I'm totally new to Elbe; trying to install and run it on Debian 10
when trying to create the initvm I'm running into the issue below.
Would appreciate some help!

kind regards
```
devel@elbe:~$ elbe initvm create
Import debian-archive-stretch-stable.gpg:
gpg: key EF0F382A1A7B6500: 2 signatures not checked due to missing keys
gpg: key EF0F382A1A7B6500: public key "Debian Stable Release Key (9/stretch) <debian-release@lists.debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Import debian-archive-buster-security-automatic.gpg:
gpg: key 4DFAB270CAA96DFA: 4 signatures not checked due to missing keys
gpg: key 4DFAB270CAA96DFA: public key "Debian Security Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1


...etc...


--2022-10-10 16:27:48--  http://ftp.de.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
Connecting to 192.168.40.69:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 6962016 (6.6M)
Saving to: ‘/tmp/tmpblsh8eg_/vmlinuz’

/tmp/tmpblsh8eg_/vmlinuz                                    100%[===========================================================================================================================================>]   6.64M  11.7MB/s    in 0.6s

2022-10-10 16:27:49 (11.7 MB/s) - ‘/tmp/tmpblsh8eg_/vmlinuz’ saved [6962016/6962016]

[CMD] gpg --no-options                 --no-default-keyring                 --keyring /home/devel/initvm/.elbe-in/elbe-keyring --import
gpg: WARNING: unsafe permissions on homedir '/home/devel/initvm/.elbe-in'
gpg: keybox '/home/devel/initvm/.elbe-in/elbe-keyring' created
gpg: key 36AA35FF22BB8F84: 1 signature not checked due to a missing key
gpg: /home/devel/initvm/.elbe-in/trustdb.gpg: trustdb created
gpg: key 36AA35FF22BB8F84: public key "ELBE Devel (Linutronix Elbe developers) <elbe-devel@linutronix.de>" imported
gpg: key 36AA35FF22BB8F84: 1 signature not checked due to a missing key
gpg: key 36AA35FF22BB8F84: "ELBE Devel (Linutronix Elbe developers) <elbe-devel@linutronix.de>" not changed
gpg: Total number processed: 2
gpg:               imported: 1
gpg:              unchanged: 1
gpg: no ultimately trusted keys found
gpg: WARNING: unsafe permissions on homedir '/home/devel/initvm/.elbe-in'
gpg: keybox '/home/devel/initvm/.elbe-in/elbe-keyring' created
gpg: key 36AA35FF22BB8F84: 1 signature not checked due to a missing key
gpg: /home/devel/initvm/.elbe-in/trustdb.gpg: trustdb created
gpg: key 36AA35FF22BB8F84: public key "ELBE Devel (Linutronix Elbe developers) <elbe-devel@linutronix.de>" imported
gpg: key 36AA35FF22BB8F84: 1 signature not checked due to a missing key
gpg: key 36AA35FF22BB8F84: "ELBE Devel (Linutronix Elbe developers) <elbe-devel@linutronix.de>" not changed
gpg: Total number processed: 2
gpg:               imported: 1
gpg:              unchanged: 1
gpg: no ultimately trusted keys found
[CMD] gpg --no-options                 --no-default-keyring                 --keyring /home/devel/initvm/.elbe-in/elbe-keyring                 --export                 --output /home/devel/initvm/.elbe-in/elbe-keyring.gpg
libvirt: Capabilities Utils error : invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm
Traceback (most recent call last):
  File "/usr/bin/elbe", line 60, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/usr/lib/python3/dist-packages/elbepack/commands/initvm.py", line 96, in run_command
    action.execute(directory, opt, args[1:])
  File "/usr/lib/python3/dist-packages/elbepack/initvmaction.py", line 598, in execute
    self.conn.defineXML(xml)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 3750, in defineXML
    if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirt.libvirtError: invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm

```

**Comment by bgermann** [comment]
It turns out that you find #248 by searching for the error.
