### ISSUE TITLE
_ped.PartitionException: Unable to satisfy all constraints on the partition.

### ISSUE THREAD

**Issue by coveritytest** [Linutronix/elbe#352]
This works:

```
		<images>
			<!-- use GPT for UEFI -->
			<gpthd>
				<name>sda.img</name>
				<size>16GiB</size>
				<!-- install grub -->
				<grub-install/>
				<!-- the EFI system partition -->
				<partition> 
					<size>200MiB</size>
					<label>uefi</label>
					<bootable>true</bootable>
				</partition>
				<partition>
					<size>6GiB</size>
					<label>rfs</label>
				</partition>
				<partition>
					<size>6GiB</size>
					<label>rfs2</label>
				</partition>
			</gpthd>
		</images>
```

This gives the error on the bottom:

```
		<images>
			<!-- use GPT for UEFI -->
			<gpthd>
				<name>sda.img</name>
				<size>65GiB</size>
				<!-- install grub -->
				<grub-install/>
				<!-- the EFI system partition -->
				<partition> 
					<size>1GiB</size>
					<label>uefi</label>
					<bootable>true</bootable>
				</partition>
				<partition>
					<size>32GiB</size>
					<label>rfs</label>
				</partition>
				<partition>
					<size>32GiB</size>
					<label>rfs2</label>
				</partition>
			</gpthd>
		</images>
```

```
[ERROR] Build failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/elbepack/asyncworker.py", line 183, in execute
    self.project.build(skip_pkglist=False,
  File "/usr/lib/python3/dist-packages/elbepack/elbeproject.py", line 686, in build
    self.targetfs.part_target(self.builddir, grub_version, grub_fw_type)
  File "/usr/lib/python3/dist-packages/elbepack/efilesystem.py", line 423, in part_target
    hdimages = do_hdimg(self.xml,
  File "/usr/lib/python3/dist-packages/elbepack/hdimg.py", line 599, in do_hdimg
    img = do_image_hd(i,
  File "/usr/lib/python3/dist-packages/elbepack/hdimg.py", line 471, in do_image_hd
    ppart = create_partition(
  File "/usr/lib/python3/dist-packages/elbepack/hdimg.py", line 341, in create_partition
    disk.addPartition(ppart, cons)
  File "/usr/lib/python3/dist-packages/parted/decorators.py", line 42, in new
    ret = fn(*args, **kwds)
  File "/usr/lib/python3/dist-packages/parted/disk.py", line 244, in addPartition
    result = self.__disk.add_partition(partition.getPedPartition(),
_ped.PartitionException: Unable to satisfy all constraints on the partition.
```

Why?

**Comment by bgermann** [comment]
1GiB+32GiB+32GiB+partition table size > 65GiB
