### ISSUE TITLE
set_xml backtrace instead of human readable errror

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#86]
./elbe control --user manut --pass XXX set_xml examples/x86_64-pc-hdimg-minimal-grub-jessie.xml /var/cache/elbe/d7b7c2ee-3b2c-4d57-9ed2-b918c3cc3762  
Traceback (most recent call last):
  File "./elbe", line 61, in <module>
    cmdmod.run_command( sys.argv[2:] )
  File "/home/local/projects/elbe/elbe/elbepack/commands/control.py", line 143, in run_command
    action.execute (control, opt, args[1:])
  File "/home/local/projects/elbe/elbe/elbepack/soapclient.py", line 223, in execute
    x = ElbeXML (filename, skip_validate=True, skip_urlcheck=True)
  File "/home/local/projects/elbe/elbe/elbepack/elbexml.py", line 59, in __init__
    self.xml = etree( fname )
  File "/home/local/projects/elbe/elbe/elbepack/treeutils.py", line 119, in __init__
    et = parse (fname, parser=parser)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:79841)
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:116175)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:116525)
  File "src/lxml/parser.pxi", line 1723, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:115413)
  File "src/lxml/parser.pxi", line 1126, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:110110)
  File "src/lxml/parser.pxi", line 584, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103584)
  File "src/lxml/parser.pxi", line 694, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105238)
  File "src/lxml/parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:104104)
IOError: Error reading file '/var/cache/elbe/d7b7c2ee-3b2c-4d57-9ed2-b918c3cc3762': failed to load external entity "/var/cache/elbe/d7b7c2ee-3b2c-4d57-9ed2-b918c3cc3762"

**Comment by manut** [comment]
fixed: fc7d569b5071c585ffa421e9539539c80c4663a0
